/// Generated by Claude 

// Bangumi types
export type SourceType = "webrip" | "bdrip";

export interface Bangumi {
  id: number;
  created_at: string;
  updated_at: string;
  title_chinese: string;
  title_japanese: string | null;
  season: number;
  year: number;
  bgmtv_id: number | null;
  tmdb_id: number | null;
  poster_url: string | null;
  air_date: string | null;
  total_episodes: number;
  episode_offset: number;
  current_episode: number;
  auto_download: boolean;
  save_path: string | null;
  source_type: SourceType;
}

export interface CreateBangumiRequest {
  title_chinese: string;
  title_japanese?: string | null;
  season?: number;
  year: number;
  bgmtv_id?: number | null;
  tmdb_id?: number | null;
  poster_url?: string | null;
  air_date?: string | null;
  total_episodes?: number;
  episode_offset?: number;
  auto_download?: boolean;
  save_path?: string | null;
  source_type?: SourceType;
}

export interface UpdateBangumiRequest {
  title_chinese?: string;
  title_japanese?: string | null;
  season?: number;
  year?: number;
  bgmtv_id?: number | null;
  tmdb_id?: number | null;
  poster_url?: string | null;
  air_date?: string | null;
  total_episodes?: number;
  episode_offset?: number;
  current_episode?: number;
  auto_download?: boolean;
  save_path?: string | null;
  source_type?: SourceType;
}

// BGM.tv Search types
export type Platform = "TV" | "Web" | "DLC" | "剧场版" | "Unknown";

export interface Subject {
  id: number;
  name: string;
  name_cn: string;
  date: string | null;
  platform: Platform | null;
  image: string | null;
  eps: number;
}

export interface SearchSubjectsResponse {
  total: number;
  limit: number;
  offset: number;
  data: Subject[];
}

// TMDB Search types
export interface TmdbTvShow {
  id: number;
  name: string;
  original_name: string;
  overview: string;
  poster_path: string | null;
  backdrop_path: string | null;
  first_air_date: string | null;
  vote_average: number;
  vote_count: number;
  popularity: number;
  genre_ids: number[];
  origin_country: string[];
  original_language: string;
}

export interface TmdbSearchResponse {
  page: number;
  results: TmdbTvShow[];
  total_pages: number;
  total_results: number;
}
