// This file is auto-generated by @hey-api/openapi-ts

export const SeriesSchema = {
  properties: {
    createdAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    posterUrl: {
      type: "string",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    updatedAt: {
      $ref: "#/components/schemas/UTCTime",
    },
  },
  required: ["id", "createdAt", "updatedAt", "titleChinese"],
  type: "object",
} as const;

export const UTCTimeSchema = {
  example: "2016-07-22T00:00:00Z",
  format: "yyyy-mm-ddThh:MM:ssZ",
  type: "string",
} as const;

export const BangumiSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeek: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    createdAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mikanId: {
      type: "string",
    },
    platform: {
      $ref: "#/components/schemas/Platform",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    tmdbId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    tmdbLookupAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    totalEpisodes: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    updatedAt: {
      $ref: "#/components/schemas/UTCTime",
    },
  },
  required: [
    "id",
    "createdAt",
    "updatedAt",
    "titleChinese",
    "season",
    "platform",
    "totalEpisodes",
    "airWeek",
  ],
  type: "object",
} as const;

export const PlatformSchema = {
  description: "Platform type for bangumi (tv, movie, ova)",
  enum: ["tv", "movie", "ova"],
  type: "string",
} as const;

export const CreateBangumiDTOSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeek: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mikanId: {
      type: "string",
    },
    platform: {
      $ref: "#/components/schemas/Platform",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    tmdbId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    totalEpisodes: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: ["titleChinese"],
  type: "object",
} as const;

export const UpdateBangumiDTOSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeek: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mikanId: {
      type: "string",
    },
    platform: {
      $ref: "#/components/schemas/Platform",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    tmdbId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    totalEpisodes: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  type: "object",
} as const;

export const SubscribedBangumiSchema = {
  properties: {
    bangumi: {
      $ref: "#/components/schemas/Bangumi",
    },
    rssEntries: {
      items: {
        $ref: "#/components/schemas/Rss",
      },
      type: "array",
    },
    subscription: {
      $ref: "#/components/schemas/Subscription",
    },
  },
  required: ["subscription", "bangumi", "rssEntries"],
  type: "object",
} as const;

export const SubscriptionSchema = {
  properties: {
    autoComplete: {
      type: "boolean",
    },
    bangumiId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    createdAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    currentEpisode: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    embyId: {
      type: "string",
    },
    episodeOffset: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    savePath: {
      type: "string",
    },
    sourceType: {
      $ref: "#/components/schemas/SourceType",
    },
    updatedAt: {
      $ref: "#/components/schemas/UTCTime",
    },
  },
  required: [
    "id",
    "createdAt",
    "updatedAt",
    "bangumiId",
    "currentEpisode",
    "autoComplete",
    "sourceType",
    "episodeOffset",
  ],
  type: "object",
} as const;

export const SourceTypeSchema = {
  description: "Source type for bangumi (bdrip, other)",
  enum: ["bdrip", "other"],
  type: "string",
} as const;

export const RssSchema = {
  properties: {
    createdAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    enabled: {
      type: "boolean",
    },
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    lastProcessedPubDate: {
      type: "string",
    },
    subscriptionId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    updatedAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    url: {
      type: "string",
    },
  },
  required: [
    "id",
    "createdAt",
    "updatedAt",
    "subscriptionId",
    "url",
    "enabled",
  ],
  type: "object",
} as const;

export const SubscribeDTOSchema = {
  properties: {
    autoComplete: {
      type: "boolean",
    },
    currentEpisode: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    episodeOffset: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    rssUrl: {
      type: "string",
    },
    savePath: {
      type: "string",
    },
    sourceType: {
      $ref: "#/components/schemas/SourceType",
    },
  },
  type: "object",
} as const;

export const UpdateSubscriptionDTOSchema = {
  properties: {
    autoComplete: {
      type: "boolean",
    },
    currentEpisode: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    embyId: {
      type: "string",
    },
    episodeOffset: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    savePath: {
      type: "string",
    },
    sourceType: {
      $ref: "#/components/schemas/SourceType",
    },
  },
  type: "object",
} as const;

export const CalendarDaySchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/CalendarSubject",
      },
      type: "array",
    },
    weekday: {
      $ref: "#/components/schemas/Weekday",
    },
  },
  required: ["weekday", "items"],
  type: "object",
} as const;

export const WeekdaySchema = {
  properties: {
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
  required: ["id", "name"],
  type: "object",
} as const;

export const CalendarSubjectSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeek: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mikanId: {
      type: "string",
    },
    platform: {
      $ref: "#/components/schemas/Platform",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    subscribed: {
      type: "boolean",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    tmdbId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    totalEpisodes: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: [
    "titleChinese",
    "airWeek",
    "totalEpisodes",
    "season",
    "platform",
    "subscribed",
  ],
  type: "object",
} as const;

export const QuickSubscribeDTOSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeek: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mikanId: {
      type: "string",
    },
    platform: {
      $ref: "#/components/schemas/Platform",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    totalEpisodes: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: [
    "mikanId",
    "titleChinese",
    "airWeek",
    "totalEpisodes",
    "season",
    "platform",
  ],
  type: "object",
} as const;

export const LogsResponseSchema = {
  properties: {
    entries: {
      items: {
        $ref: "#/components/schemas/LogEntry",
      },
      type: "array",
    },
    page: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    pageSize: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    total: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: ["entries", "total", "page", "pageSize"],
  type: "object",
} as const;

export const LogEntrySchema = {
  description:
    "A structured log entry with timestamp, level, message, component, and optional metadata",
  type: "object",
} as const;

export const TorrentSchema = {
  properties: {
    createdAt: {
      $ref: "#/components/schemas/UTCTime",
    },
    episodeNumber: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    group: {
      type: "string",
    },
    id: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    infoHash: {
      type: "string",
    },
    languages: {
      items: {
        $ref: "#/components/schemas/Subtitle",
      },
      type: "array",
    },
    rssId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    subscriptionId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    torrentUrl: {
      type: "string",
    },
    updatedAt: {
      $ref: "#/components/schemas/UTCTime",
    },
  },
  required: [
    "id",
    "createdAt",
    "updatedAt",
    "subscriptionId",
    "infoHash",
    "torrentUrl",
    "languages",
  ],
  type: "object",
} as const;

export const SubtitleSchema = {
  enum: ["CHT", "CHS", "JAP", "ENG"],
  type: "string",
} as const;

export const AddTorrentDTOSchema = {
  properties: {
    episodeNumber: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    subscriptionId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    torrentUrl: {
      type: "string",
    },
  },
  required: ["torrentUrl", "subscriptionId", "episodeNumber"],
  type: "object",
} as const;

export const TestNotificationRequestSchema = {
  properties: {
    botToken: {
      type: "string",
    },
    chatId: {
      type: "string",
    },
  },
  required: ["botToken", "chatId"],
  type: "object",
} as const;

export const EmbyLibraryInfoSchema = {
  properties: {
    collectionType: {
      type: "string",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
  required: ["id", "name"],
  type: "object",
} as const;

export const ImportResultSchema = {
  properties: {
    records: {
      items: {
        $ref: "#/components/schemas/ImportRecord",
      },
      type: "array",
    },
    stats: {
      $ref: "#/components/schemas/ImportStats",
    },
  },
  required: ["stats", "records"],
  type: "object",
} as const;

export const ImportStatsSchema = {
  properties: {
    failed: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    imported: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    skipped: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    total: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: ["total", "imported", "skipped", "failed"],
  type: "object",
} as const;

export const ImportRecordSchema = {
  properties: {
    bangumiId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    embyId: {
      type: "string",
    },
    error_: {
      type: "string",
    },
    status: {
      $ref: "#/components/schemas/ImportStatus",
    },
    title: {
      type: "string",
    },
  },
  required: ["embyId", "title", "status"],
  type: "object",
} as const;

export const ImportStatusSchema = {
  enum: ["Imported", "Skipped", "Failed"],
  type: "string",
} as const;

export const ImportEmbyRequestSchema = {
  properties: {
    libraryIds: {
      items: {
        type: "string",
      },
      type: "array",
    },
  },
  type: "object",
} as const;

export const TestEmbyResponseSchema = {
  properties: {
    libraryCount: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    message: {
      type: "string",
    },
    success: {
      type: "boolean",
    },
  },
  required: ["success", "message"],
  type: "object",
} as const;

export const TestEmbyRequestSchema = {
  properties: {
    settings: {
      $ref: "#/components/schemas/EmbySettings",
    },
  },
  required: ["settings"],
  type: "object",
} as const;

export const EmbySettingsSchema = {
  properties: {
    apiKey: {
      type: "string",
    },
    url: {
      type: "string",
    },
  },
  required: ["url", "apiKey"],
  type: "object",
} as const;

export const TestDownloaderResponseSchema = {
  properties: {
    message: {
      type: "string",
    },
    success: {
      type: "boolean",
    },
  },
  required: ["success", "message"],
  type: "object",
} as const;

export const TestDownloaderRequestSchema = {
  properties: {
    settings: {
      $ref: "#/components/schemas/DownloaderSettings",
    },
  },
  required: ["settings"],
  type: "object",
} as const;

export const DownloaderSettingsSchema = {
  properties: {
    password: {
      type: "string",
    },
    savePath: {
      type: "string",
    },
    url: {
      type: "string",
    },
    username: {
      type: "string",
    },
  },
  required: ["url", "username", "password", "savePath"],
  type: "object",
} as const;

export const SettingsSchema = {
  properties: {
    downloader: {
      $ref: "#/components/schemas/DownloaderSettings",
    },
    emby: {
      $ref: "#/components/schemas/EmbySettings",
    },
    filter_: {
      $ref: "#/components/schemas/FilterSettings",
    },
    notification: {
      $ref: "#/components/schemas/NotificationSettings",
    },
    priority: {
      $ref: "#/components/schemas/PrioritySettings",
    },
    tmdb: {
      $ref: "#/components/schemas/TmdbSettings",
    },
  },
  required: [
    "downloader",
    "filter_",
    "notification",
    "priority",
    "tmdb",
    "emby",
  ],
  type: "object",
} as const;

export const FilterSettingsSchema = {
  properties: {
    globalRssFilters: {
      items: {
        type: "string",
      },
      type: "array",
    },
  },
  required: ["globalRssFilters"],
  type: "object",
} as const;

export const NotificationSettingsSchema = {
  properties: {
    telegram: {
      $ref: "#/components/schemas/TelegramConfig",
    },
  },
  required: ["telegram"],
  type: "object",
} as const;

export const TelegramConfigSchema = {
  properties: {
    botToken: {
      type: "string",
    },
    chatId: {
      type: "string",
    },
  },
  required: ["botToken", "chatId"],
  type: "object",
} as const;

export const PrioritySettingsSchema = {
  properties: {
    groups: {
      items: {
        type: "string",
      },
      type: "array",
    },
    languages: {
      items: {
        $ref: "#/components/schemas/SubtitlePattern",
      },
      type: "array",
    },
  },
  required: ["groups", "languages"],
  type: "object",
} as const;

export const SubtitlePatternSchema = {
  description:
    'Subtitle pattern as array of language codes, e.g. ["CHS", "JAP"] for 简日',
  items: {
    $ref: "#/components/schemas/Subtitle",
  },
  type: "array",
} as const;

export const TmdbSettingsSchema = {
  properties: {
    apiKey: {
      type: "string",
    },
  },
  required: ["apiKey"],
  type: "object",
} as const;

export const BgmtvSearchItemSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    id: {
      format: "int64",
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    posterUrl: {
      type: "string",
    },
    season: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    totalEpisodes: {
      format: "int64",
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: [
    "id",
    "titleChinese",
    "titleJapanese",
    "posterUrl",
    "airDate",
    "totalEpisodes",
    "season",
  ],
  type: "object",
} as const;

export const TmdbSearchItemSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    id: {
      format: "int64",
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    mediaType: {
      $ref: "#/components/schemas/TmdbMediaType",
    },
    name: {
      type: "string",
    },
    posterPath: {
      type: "string",
    },
  },
  required: ["id", "name", "mediaType"],
  type: "object",
} as const;

export const TmdbMediaTypeSchema = {
  enum: ["TmdbMovie", "TmdbTv"],
  type: "string",
} as const;

export const MikanSearchResultSchema = {
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
  required: ["id", "name"],
  type: "object",
} as const;

export const MikanBangumiDetailSchema = {
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    subgroups: {
      items: {
        $ref: "#/components/schemas/MikanSubgroup",
      },
      type: "array",
    },
  },
  required: ["id", "name", "subgroups"],
  type: "object",
} as const;

export const MikanSubgroupSchema = {
  properties: {
    episodes: {
      items: {
        $ref: "#/components/schemas/MikanEpisode",
      },
      type: "array",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    rssUrl: {
      type: "string",
    },
  },
  required: ["id", "rssUrl", "episodes"],
  type: "object",
} as const;

export const MikanEpisodeSchema = {
  properties: {
    name: {
      type: "string",
    },
  },
  required: ["name"],
  type: "object",
} as const;

export const EpisodeInfoSchema = {
  properties: {
    airdate: {
      type: "string",
    },
    ep: {
      format: "double",
      type: "number",
    },
    id: {
      format: "int64",
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    name: {
      type: "string",
    },
    nameCn: {
      type: "string",
    },
    sort: {
      format: "double",
      type: "number",
    },
  },
  required: ["id", "sort", "name", "nameCn", "airdate"],
  type: "object",
} as const;

export const CalendarItemSchema = {
  properties: {
    airDate: {
      type: "string",
    },
    airWeekday: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    bgmtvId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
    itemType: {
      type: "string",
    },
    mikanId: {
      type: "string",
    },
    officialSite: {
      type: "string",
    },
    titleChinese: {
      type: "string",
    },
    titleJapanese: {
      type: "string",
    },
    tmdbId: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: "integer",
    },
  },
  required: ["titleChinese", "titleJapanese", "airWeekday", "itemType"],
  type: "object",
} as const;
