// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CleanupLogsData,
  CleanupLogsErrors,
  CleanupLogsResponses,
  CreateBangumiData,
  CreateBangumiErrors,
  CreateBangumiResponses,
  DeleteTorrentsData,
  DeleteTorrentsErrors,
  DeleteTorrentsResponses,
  GetBangumiByIdData,
  GetBangumiByIdErrors,
  GetBangumiByIdResponses,
  GetBangumiData,
  GetBangumiErrors,
  GetBangumiResponses,
  GetEpisodesData,
  GetEpisodesErrors,
  GetEpisodesResponses,
  GetLogsData,
  GetLogsErrors,
  GetLogsResponses,
  GetMikanRssData,
  GetMikanRssErrors,
  GetMikanRssResponses,
  GetSettingsData,
  GetSettingsErrors,
  GetSettingsResponses,
  ListTorrentsData,
  ListTorrentsErrors,
  ListTorrentsResponses,
  PauseTorrentsData,
  PauseTorrentsErrors,
  PauseTorrentsResponses,
  ResetSettingsData,
  ResetSettingsErrors,
  ResetSettingsResponses,
  ResumeTorrentsData,
  ResumeTorrentsErrors,
  ResumeTorrentsResponses,
  SearchBgmtvData,
  SearchBgmtvErrors,
  SearchBgmtvResponses,
  SearchMikanData,
  SearchMikanErrors,
  SearchMikanResponses,
  SearchTmdbData,
  SearchTmdbErrors,
  SearchTmdbResponses,
  StreamLogsData,
  StreamLogsResponses,
  SyncMaindataData,
  SyncMaindataErrors,
  SyncMaindataResponses,
  TestDownloaderConnectionData,
  TestDownloaderConnectionErrors,
  TestDownloaderConnectionResponses,
  TorrentCompletedData,
  TorrentCompletedErrors,
  TorrentCompletedResponses,
  TriggerRssFetchData,
  TriggerRssFetchErrors,
  TriggerRssFetchResponses,
  UpdateBangumiData,
  UpdateBangumiErrors,
  UpdateBangumiResponses,
  UpdateSettingsData,
  UpdateSettingsErrors,
  UpdateSettingsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all bangumi
 */
export const getBangumi = <ThrowOnError extends boolean = false>(
  options?: Options<GetBangumiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetBangumiResponses,
    GetBangumiErrors,
    ThrowOnError
  >({ url: "/api/bangumi", ...options });

/**
 * Create a new bangumi
 */
export const createBangumi = <ThrowOnError extends boolean = false>(
  options: Options<CreateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBangumiResponses,
    CreateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a bangumi by ID with its RSS subscriptions
 */
export const getBangumiById = <ThrowOnError extends boolean = false>(
  options: Options<GetBangumiByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBangumiByIdResponses,
    GetBangumiByIdErrors,
    ThrowOnError
  >({ url: "/api/bangumi/{id}", ...options });

/**
 * Update a bangumi
 */
export const updateBangumi = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateBangumiResponses,
    UpdateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Test downloader connection with provided credentials
 */
export const testDownloaderConnection = <ThrowOnError extends boolean = false>(
  options: Options<TestDownloaderConnectionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TestDownloaderConnectionResponses,
    TestDownloaderConnectionErrors,
    ThrowOnError
  >({
    url: "/api/downloader/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(
  options: Options<GetEpisodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEpisodesResponses,
    GetEpisodesErrors,
    ThrowOnError
  >({ url: "/api/episodes/{subject_id}", ...options });

/**
 * Delete old logs (cleanup endpoint)
 */
export const cleanupLogs = <ThrowOnError extends boolean = false>(
  options?: Options<CleanupLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    CleanupLogsResponses,
    CleanupLogsErrors,
    ThrowOnError
  >({ url: "/api/logs", ...options });

/**
 * Get logs with optional filtering and pagination
 */
export const getLogs = <ThrowOnError extends boolean = false>(
  options?: Options<GetLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetLogsResponses,
    GetLogsErrors,
    ThrowOnError
  >({ url: "/api/logs", ...options });

/**
 * Stream logs via Server-Sent Events (SSE)
 */
export const streamLogs = <ThrowOnError extends boolean = false>(
  options?: Options<StreamLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).sse.get<
    StreamLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/logs/stream", ...options });

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRss = <ThrowOnError extends boolean = false>(
  options: Options<GetMikanRssData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMikanRssResponses,
    GetMikanRssErrors,
    ThrowOnError
  >({ url: "/api/mikan/rss", ...options });

/**
 * Manually trigger RSS fetch job
 */
export const triggerRssFetch = <ThrowOnError extends boolean = false>(
  options?: Options<TriggerRssFetchData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    TriggerRssFetchResponses,
    TriggerRssFetchErrors,
    ThrowOnError
  >({ url: "/api/scheduler/rss-fetch", ...options });

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtv = <ThrowOnError extends boolean = false>(
  options: Options<SearchBgmtvData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchBgmtvResponses,
    SearchBgmtvErrors,
    ThrowOnError
  >({ url: "/api/search/bgmtv", ...options });

/**
 * Search for bangumi on Mikan
 */
export const searchMikan = <ThrowOnError extends boolean = false>(
  options: Options<SearchMikanData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchMikanResponses,
    SearchMikanErrors,
    ThrowOnError
  >({ url: "/api/search/mikan", ...options });

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdb = <ThrowOnError extends boolean = false>(
  options: Options<SearchTmdbData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchTmdbResponses,
    SearchTmdbErrors,
    ThrowOnError
  >({ url: "/api/search/tmdb", ...options });

/**
 * Get application settings
 */
export const getSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSettingsResponses,
    GetSettingsErrors,
    ThrowOnError
  >({ url: "/api/settings", ...options });

/**
 * Update application settings
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateSettingsResponses,
    UpdateSettingsErrors,
    ThrowOnError
  >({
    url: "/api/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset settings to defaults
 */
export const resetSettings = <ThrowOnError extends boolean = false>(
  options?: Options<ResetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ResetSettingsResponses,
    ResetSettingsErrors,
    ThrowOnError
  >({ url: "/api/settings/reset", ...options });

/**
 * List all torrents
 */
export const listTorrents = <ThrowOnError extends boolean = false>(
  options?: Options<ListTorrentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTorrentsResponses,
    ListTorrentsErrors,
    ThrowOnError
  >({ url: "/api/torrents", ...options });

/**
 * Delete torrents
 */
export const deleteTorrents = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTorrentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeleteTorrentsResponses,
    DeleteTorrentsErrors,
    ThrowOnError
  >({
    url: "/api/torrents/delete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Pause torrents
 */
export const pauseTorrents = <ThrowOnError extends boolean = false>(
  options: Options<PauseTorrentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PauseTorrentsResponses,
    PauseTorrentsErrors,
    ThrowOnError
  >({
    url: "/api/torrents/pause",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Resume torrents
 */
export const resumeTorrents = <ThrowOnError extends boolean = false>(
  options: Options<ResumeTorrentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResumeTorrentsResponses,
    ResumeTorrentsErrors,
    ThrowOnError
  >({
    url: "/api/torrents/resume",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Sync maindata for incremental torrent updates
 *
 * Returns full torrent data on first call (rid=0), then incremental changes on subsequent calls.
 * Use the returned `rid` value in the next request to get only changed data.
 */
export const syncMaindata = <ThrowOnError extends boolean = false>(
  options?: Options<SyncMaindataData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SyncMaindataResponses,
    SyncMaindataErrors,
    ThrowOnError
  >({ url: "/api/torrents/sync", ...options });

/**
 * Webhook endpoint for qBittorrent torrent completion callback.
 *
 * Configure qBittorrent to call this endpoint when a torrent finishes downloading:
 * Settings -> Downloads -> "Run external program on torrent finished"
 * Command: `curl -X POST "http://your-server:3000/api/webhook/torrent-completed?hash=%I"`
 *
 * The `%I` placeholder will be replaced with the torrent's info hash.
 */
export const torrentCompleted = <ThrowOnError extends boolean = false>(
  options: Options<TorrentCompletedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TorrentCompletedResponses,
    TorrentCompletedErrors,
    ThrowOnError
  >({ url: "/api/webhook/torrent-completed", ...options });
