// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateBangumiData,
  CreateBangumiErrors,
  CreateBangumiResponses,
  GetEpisodesData,
  GetEpisodesErrors,
  GetEpisodesResponses,
  SearchBangumiData,
  SearchBangumiErrors,
  SearchBangumiResponses,
  SearchTmdbData,
  SearchTmdbErrors,
  SearchTmdbResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create a new bangumi
 */
export const createBangumi = <ThrowOnError extends boolean = false>(
  options: Options<CreateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBangumiResponses,
    CreateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(
  options: Options<GetEpisodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEpisodesResponses,
    GetEpisodesErrors,
    ThrowOnError
  >({ url: "/api/episodes/{subject_id}", ...options });

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBangumi = <ThrowOnError extends boolean = false>(
  options: Options<SearchBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchBangumiResponses,
    SearchBangumiErrors,
    ThrowOnError
  >({ url: "/api/search/bgmtv", ...options });

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdb = <ThrowOnError extends boolean = false>(
  options: Options<SearchTmdbData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchTmdbResponses,
    SearchTmdbErrors,
    ThrowOnError
  >({ url: "/api/search/tmdb", ...options });
