// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AddTorrentData,
  AddTorrentErrors,
  AddTorrentResponses,
  CreateBangumiData,
  CreateBangumiErrors,
  CreateBangumiResponses,
  DeleteApiBangumiByIdData,
  DeleteApiBangumiByIdErrors,
  DeleteApiBangumiByIdResponses,
  DeleteApiBangumiSubscriptionsBySubscriptionIdData,
  DeleteApiBangumiSubscriptionsBySubscriptionIdErrors,
  DeleteApiBangumiSubscriptionsBySubscriptionIdResponses,
  GetApiBangumiSubscriptionsBySubscriptionIdData,
  GetApiBangumiSubscriptionsBySubscriptionIdErrors,
  GetApiBangumiSubscriptionsBySubscriptionIdResponses,
  GetApiBangumiSubscriptionsData,
  GetApiBangumiSubscriptionsResponses,
  GetApiMetadataBangumiDataData,
  GetApiMetadataBangumiDataErrors,
  GetApiMetadataBangumiDataResponses,
  GetApiMetadataSearchBgmtvData,
  GetApiMetadataSearchBgmtvErrors,
  GetApiMetadataSearchBgmtvResponses,
  GetApiMetadataSearchTmdbData,
  GetApiMetadataSearchTmdbErrors,
  GetApiMetadataSearchTmdbResponses,
  GetBangumiData,
  GetBangumiErrors,
  GetBangumiResponses,
  GetCalendarData,
  GetCalendarErrors,
  GetCalendarResponses,
  GetEmbyLibrariesData,
  GetEmbyLibrariesResponses,
  GetEpisodesData,
  GetEpisodesErrors,
  GetEpisodesResponses,
  GetLogsData,
  GetLogsErrors,
  GetLogsResponses,
  GetMikanRssData,
  GetMikanRssErrors,
  GetMikanRssResponses,
  GetSettingsData,
  GetSettingsResponses,
  ImportEmbyData,
  ImportEmbyErrors,
  ImportEmbyResponses,
  ListBangumiData,
  ListBangumiResponses,
  ListSeriesData,
  ListSeriesResponses,
  PatchApiBangumiSubscriptionsBySubscriptionIdData,
  PatchApiBangumiSubscriptionsBySubscriptionIdErrors,
  PatchApiBangumiSubscriptionsBySubscriptionIdResponses,
  PostApiBangumiByIdSubscribeData,
  PostApiBangumiByIdSubscribeErrors,
  PostApiBangumiByIdSubscribeResponses,
  PostApiCalendarQuickSubscribeData,
  PostApiCalendarQuickSubscribeErrors,
  PostApiCalendarQuickSubscribeResponses,
  PostApiDownloaderTestData,
  PostApiDownloaderTestErrors,
  PostApiDownloaderTestResponses,
  RefreshCalendarData,
  RefreshCalendarErrors,
  RefreshCalendarResponses,
  SearchMikanData,
  SearchMikanErrors,
  SearchMikanResponses,
  StreamLogsData,
  StreamLogsResponses,
  TestEmbyData,
  TestEmbyErrors,
  TestEmbyResponses,
  TestNotificationData,
  TestNotificationErrors,
  TestNotificationResponses,
  UpdateBangumiData,
  UpdateBangumiErrors,
  UpdateBangumiResponses,
  UpdateSettingsData,
  UpdateSettingsErrors,
  UpdateSettingsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all series
 */
export const listSeries = <ThrowOnError extends boolean = false>(
  options?: Options<ListSeriesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListSeriesResponses, unknown, ThrowOnError>({
    url: "/api/series",
    ...options,
  });

/**
 * Get all bangumi metadata
 */
export const listBangumi = <ThrowOnError extends boolean = false>(
  options?: Options<ListBangumiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListBangumiResponses, unknown, ThrowOnError>({
    url: "/api/bangumi",
    ...options,
  });

/**
 * Create a new bangumi (metadata only)
 */
export const createBangumi = <ThrowOnError extends boolean = false>(
  options?: Options<CreateBangumiData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateBangumiResponses,
    CreateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Delete bangumi
 */
export const deleteApiBangumiById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiBangumiByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiBangumiByIdResponses,
    DeleteApiBangumiByIdErrors,
    ThrowOnError
  >({ url: "/api/bangumi/{id}", ...options });

/**
 * Get bangumi by ID
 */
export const getBangumi = <ThrowOnError extends boolean = false>(
  options: Options<GetBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBangumiResponses,
    GetBangumiErrors,
    ThrowOnError
  >({ url: "/api/bangumi/{id}", ...options });

/**
 * Update bangumi metadata
 */
export const updateBangumi = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateBangumiResponses,
    UpdateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options.headers,
    },
  });

/**
 * Get all subscribed bangumi
 */
export const getApiBangumiSubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiBangumiSubscriptionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiBangumiSubscriptionsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/bangumi/subscriptions", ...options });

/**
 * Unsubscribe from a bangumi
 */
export const deleteApiBangumiSubscriptionsBySubscriptionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteApiBangumiSubscriptionsBySubscriptionIdData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteApiBangumiSubscriptionsBySubscriptionIdResponses,
    DeleteApiBangumiSubscriptionsBySubscriptionIdErrors,
    ThrowOnError
  >({ url: "/api/bangumi/subscriptions/{subscriptionId}", ...options });

/**
 * Get subscription by ID
 */
export const getApiBangumiSubscriptionsBySubscriptionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetApiBangumiSubscriptionsBySubscriptionIdData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetApiBangumiSubscriptionsBySubscriptionIdResponses,
    GetApiBangumiSubscriptionsBySubscriptionIdErrors,
    ThrowOnError
  >({ url: "/api/bangumi/subscriptions/{subscriptionId}", ...options });

/**
 * Update a subscription
 */
export const patchApiBangumiSubscriptionsBySubscriptionId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchApiBangumiSubscriptionsBySubscriptionIdData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    PatchApiBangumiSubscriptionsBySubscriptionIdResponses,
    PatchApiBangumiSubscriptionsBySubscriptionIdErrors,
    ThrowOnError
  >({
    url: "/api/bangumi/subscriptions/{subscriptionId}",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options.headers,
    },
  });

/**
 * Subscribe to a bangumi
 */
export const postApiBangumiByIdSubscribe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiBangumiByIdSubscribeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiBangumiByIdSubscribeResponses,
    PostApiBangumiByIdSubscribeErrors,
    ThrowOnError
  >({
    url: "/api/bangumi/{id}/subscribe",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options.headers,
    },
  });

/**
 * Get seasonal calendar
 *
 * Get bangumi calendar for a specific year and season
 */
export const getCalendar = <ThrowOnError extends boolean = false>(
  options?: Options<GetCalendarData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCalendarResponses,
    GetCalendarErrors,
    ThrowOnError
  >({ url: "/api/calendar", ...options });

/**
 * Refresh calendar data
 *
 * Fetch fresh data from Mikan and update local calendar
 */
export const refreshCalendar = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshCalendarData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshCalendarResponses,
    RefreshCalendarErrors,
    ThrowOnError
  >({ url: "/api/calendar/refresh", ...options });

/**
 * Quick subscribe from calendar
 *
 * Create bangumi and subscription in one call with auto-generated Mikan RSS URL
 */
export const postApiCalendarQuickSubscribe = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiCalendarQuickSubscribeData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiCalendarQuickSubscribeResponses,
    PostApiCalendarQuickSubscribeErrors,
    ThrowOnError
  >({
    url: "/api/calendar/quick-subscribe",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Get logs by date
 *
 * Query log entries for a specific date with optional level filtering and pagination
 */
export const getLogs = <ThrowOnError extends boolean = false>(
  options: Options<GetLogsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetLogsResponses, GetLogsErrors, ThrowOnError>(
    { url: "/api/logs", ...options },
  );

/**
 * Stream real-time logs
 *
 * SSE endpoint for real-time log streaming (today's logs only). Client should filter by level.
 */
export const streamLogs = <ThrowOnError extends boolean = false>(
  options?: Options<StreamLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).sse.get<
    StreamLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/logs/stream", ...options });

/**
 * Manually add a torrent download
 */
export const addTorrent = <ThrowOnError extends boolean = false>(
  options?: Options<AddTorrentData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AddTorrentResponses,
    AddTorrentErrors,
    ThrowOnError
  >({
    url: "/api/torrent",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Test Telegram notification by sending a test message
 */
export const testNotification = <ThrowOnError extends boolean = false>(
  options?: Options<TestNotificationData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    TestNotificationResponses,
    TestNotificationErrors,
    ThrowOnError
  >({
    url: "/api/notification/test",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Get Emby libraries
 *
 * Get list of TV show libraries from Emby
 */
export const getEmbyLibraries = <ThrowOnError extends boolean = false>(
  options?: Options<GetEmbyLibrariesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetEmbyLibrariesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/emby/libraries", ...options });

/**
 * Import Bangumi from Emby media library
 *
 * Import anime from Emby. Optionally specify library IDs to import from.
 */
export const importEmby = <ThrowOnError extends boolean = false>(
  options?: Options<ImportEmbyData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ImportEmbyResponses,
    ImportEmbyErrors,
    ThrowOnError
  >({
    url: "/api/emby/import",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Test Emby connection
 *
 * Test connection to Emby server with provided settings
 */
export const testEmby = <ThrowOnError extends boolean = false>(
  options?: Options<TestEmbyData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    TestEmbyResponses,
    TestEmbyErrors,
    ThrowOnError
  >({
    url: "/api/emby/test",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Test qBittorrent connection
 *
 * Test connection and authentication to qBittorrent with provided settings
 */
export const postApiDownloaderTest = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiDownloaderTestData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiDownloaderTestResponses,
    PostApiDownloaderTestErrors,
    ThrowOnError
  >({
    url: "/api/downloader/test",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Get current settings
 *
 * Retrieve the current application settings
 */
export const getSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSettingsResponses, unknown, ThrowOnError>({
    url: "/api/settings",
    ...options,
  });

/**
 * Update settings
 *
 * Update the application settings (full replacement)
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).put<
    UpdateSettingsResponses,
    UpdateSettingsErrors,
    ThrowOnError
  >({
    url: "/api/settings",
    ...options,
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      ...options?.headers,
    },
  });

/**
 * Search bangumi metadata from BGM.tv
 */
export const getApiMetadataSearchBgmtv = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMetadataSearchBgmtvData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiMetadataSearchBgmtvResponses,
    GetApiMetadataSearchBgmtvErrors,
    ThrowOnError
  >({ url: "/api/metadata/search/bgmtv", ...options });

/**
 * Search bangumi metadata from TMDB
 */
export const getApiMetadataSearchTmdb = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMetadataSearchTmdbData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiMetadataSearchTmdbResponses,
    GetApiMetadataSearchTmdbErrors,
    ThrowOnError
  >({ url: "/api/metadata/search/tmdb", ...options });

/**
 * Search bangumi on Mikan
 */
export const searchMikan = <ThrowOnError extends boolean = false>(
  options: Options<SearchMikanData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchMikanResponses,
    SearchMikanErrors,
    ThrowOnError
  >({ url: "/api/metadata/mikan/search", ...options });

/**
 * Get Mikan bangumi detail with RSS URLs
 */
export const getMikanRss = <ThrowOnError extends boolean = false>(
  options: Options<GetMikanRssData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMikanRssResponses,
    GetMikanRssErrors,
    ThrowOnError
  >({ url: "/api/metadata/mikan/rss", ...options });

/**
 * Get episodes for a BGM.tv subject
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(
  options: Options<GetEpisodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEpisodesResponses,
    GetEpisodesErrors,
    ThrowOnError
  >({ url: "/api/metadata/episodes/{subject_id}", ...options });

/**
 * Lookup bangumi-data entry by BGM.tv ID and air date
 *
 * Uses airdate to determine which seasonal JSON file to fetch, then searches for matching bgmtv_id
 */
export const getApiMetadataBangumiData = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMetadataBangumiDataData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiMetadataBangumiDataResponses,
    GetApiMetadataBangumiDataErrors,
    ThrowOnError
  >({ url: "/api/metadata/bangumi-data", ...options });
