// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:3000" | (string & {});
};

export type Series = {
  createdAt: UtcTime;
  id: number;
  posterUrl?: string;
  titleChinese: string;
  titleJapanese?: string;
  updatedAt: UtcTime;
};

export type UtcTime = string;

export type Bangumi = {
  airDate?: string;
  airWeek: number;
  bgmtvId?: number;
  createdAt: UtcTime;
  id: number;
  mikanId?: string;
  platform: Platform;
  posterUrl?: string;
  season: number;
  titleChinese: string;
  titleJapanese?: string;
  tmdbId?: number;
  tmdbLookupAt?: UtcTime;
  totalEpisodes: number;
  updatedAt: UtcTime;
};

/**
 * Platform type for bangumi (tv, movie, ova)
 */
export type Platform = "tv" | "movie" | "ova";

export type CreateBangumiDto = {
  airDate?: string;
  airWeek?: number;
  bgmtvId?: number;
  mikanId?: string;
  platform?: Platform;
  posterUrl?: string;
  season?: number;
  titleChinese: string;
  titleJapanese?: string;
  tmdbId?: number;
  totalEpisodes?: number;
};

export type UpdateBangumiDto = {
  airDate?: string;
  airWeek?: number;
  bgmtvId?: number;
  mikanId?: string;
  platform?: Platform;
  posterUrl?: string;
  season?: number;
  titleChinese?: string;
  titleJapanese?: string;
  tmdbId?: number;
  totalEpisodes?: number;
};

export type SubscribedBangumi = {
  bangumi: Bangumi;
  rssEntries: Array<Rss>;
  subscription: Subscription;
};

export type Subscription = {
  autoComplete: boolean;
  bangumiId: number;
  createdAt: UtcTime;
  currentEpisode: number;
  embyId?: string;
  episodeOffset: number;
  id: number;
  savePath?: string;
  sourceType: SourceType;
  updatedAt: UtcTime;
};

/**
 * Source type for bangumi (bdrip, other)
 */
export type SourceType = "bdrip" | "other";

export type Rss = {
  createdAt: UtcTime;
  enabled: boolean;
  id: number;
  lastProcessedPubDate?: string;
  subscriptionId: number;
  updatedAt: UtcTime;
  url: string;
};

export type SubscribeDto = {
  autoComplete?: boolean;
  currentEpisode?: number;
  episodeOffset?: number;
  rssUrl?: string;
  savePath?: string;
  sourceType?: SourceType;
};

export type UpdateSubscriptionDto = {
  autoComplete?: boolean;
  currentEpisode?: number;
  embyId?: string;
  episodeOffset?: number;
  savePath?: string;
  sourceType?: SourceType;
};

export type CalendarDay = {
  items: Array<CalendarSubject>;
  weekday: Weekday;
};

export type Weekday = {
  id: number;
  name: string;
};

export type CalendarSubject = {
  airDate?: string;
  airWeek: number;
  bgmtvId?: number;
  mikanId?: string;
  platform: Platform;
  posterUrl?: string;
  season: number;
  subscribed: boolean;
  titleChinese: string;
  titleJapanese?: string;
  tmdbId?: number;
  totalEpisodes: number;
};

export type QuickSubscribeDto = {
  airDate?: string;
  airWeek: number;
  bgmtvId?: number;
  mikanId: string;
  platform: Platform;
  posterUrl?: string;
  season: number;
  titleChinese: string;
  titleJapanese?: string;
  totalEpisodes: number;
};

export type LogsResponse = {
  entries: Array<LogEntry>;
  page: number;
  pageSize: number;
  total: number;
};

/**
 * A structured log entry with timestamp, level, message, component, and optional metadata
 */
export type LogEntry = {
  [key: string]: unknown;
};

export type Torrent = {
  createdAt: UtcTime;
  episodeNumber?: number;
  group?: string;
  id: number;
  infoHash: string;
  languages: Array<Subtitle>;
  rssId?: number;
  subscriptionId: number;
  torrentUrl: string;
  updatedAt: UtcTime;
};

export type Subtitle = "CHT" | "CHS" | "JAP" | "ENG";

export type AddTorrentDto = {
  episodeNumber: number;
  subscriptionId: number;
  torrentUrl: string;
};

export type TestNotificationRequest = {
  botToken: string;
  chatId: string;
};

export type EmbyLibraryInfo = {
  collectionType?: string;
  id: string;
  name: string;
};

export type ImportResult = {
  records: Array<ImportRecord>;
  stats: ImportStats;
};

export type ImportStats = {
  failed: number;
  imported: number;
  skipped: number;
  total: number;
};

export type ImportRecord = {
  bangumiId?: number;
  embyId: string;
  error_?: string;
  status: ImportStatus;
  title: string;
};

export type ImportStatus = "Imported" | "Skipped" | "Failed";

export type ImportEmbyRequest = {
  libraryIds?: Array<string>;
};

export type TestEmbyResponse = {
  libraryCount?: number;
  message: string;
  success: boolean;
};

export type TestEmbyRequest = {
  settings: EmbySettings;
};

export type EmbySettings = {
  apiKey: string;
  url: string;
};

export type TestDownloaderResponse = {
  message: string;
  success: boolean;
};

export type TestDownloaderRequest = {
  settings: DownloaderSettings;
};

export type DownloaderSettings = {
  password: string;
  savePath: string;
  url: string;
  username: string;
};

export type Settings = {
  downloader: DownloaderSettings;
  emby: EmbySettings;
  filter_: FilterSettings;
  notification: NotificationSettings;
  priority: PrioritySettings;
  tmdb: TmdbSettings;
};

export type FilterSettings = {
  globalRssFilters: Array<string>;
};

export type NotificationSettings = {
  telegram: TelegramConfig;
};

export type TelegramConfig = {
  botToken: string;
  chatId: string;
};

export type PrioritySettings = {
  groups: Array<string>;
  languages: Array<SubtitlePattern>;
};

/**
 * Subtitle pattern as array of language codes, e.g. ["CHS", "JAP"] for 简日
 */
export type SubtitlePattern = Array<Subtitle>;

export type TmdbSettings = {
  apiKey: string;
};

export type BgmtvSearchItem = {
  airDate: string;
  id: number;
  posterUrl: string;
  season: number;
  titleChinese: string;
  titleJapanese: string;
  totalEpisodes: number;
};

export type TmdbSearchItem = {
  airDate?: string;
  id: number;
  mediaType: TmdbMediaType;
  name: string;
  posterPath?: string;
};

export type TmdbMediaType = "TmdbMovie" | "TmdbTv";

export type MikanSearchResult = {
  id: string;
  name: string;
};

export type MikanBangumiDetail = {
  id: string;
  name: string;
  subgroups: Array<MikanSubgroup>;
};

export type MikanSubgroup = {
  episodes: Array<MikanEpisode>;
  id: string;
  name?: string;
  rssUrl: string;
};

export type MikanEpisode = {
  name: string;
};

export type EpisodeInfo = {
  airdate: string;
  ep?: number;
  id: number;
  name: string;
  nameCn: string;
  sort: number;
};

export type CalendarItem = {
  airDate?: string;
  airWeekday: number;
  bgmtvId?: number;
  itemType: string;
  mikanId?: string;
  officialSite?: string;
  titleChinese: string;
  titleJapanese: string;
  tmdbId?: number;
};

export type ListSeriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/series";
};

export type ListSeriesResponses = {
  200: Array<Series>;
};

export type ListSeriesResponse = ListSeriesResponses[keyof ListSeriesResponses];

export type ListBangumiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type ListBangumiResponses = {
  200: Array<Bangumi>;
};

export type ListBangumiResponse =
  ListBangumiResponses[keyof ListBangumiResponses];

export type CreateBangumiData = {
  body?: CreateBangumiDto;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type CreateBangumiErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type CreateBangumiResponses = {
  200: Bangumi;
};

export type CreateBangumiResponse =
  CreateBangumiResponses[keyof CreateBangumiResponses];

export type DeleteApiBangumiByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type DeleteApiBangumiByIdErrors = {
  /**
   * `id` not found
   */
  404: unknown;
};

export type DeleteApiBangumiByIdResponses = {
  204: void;
};

export type DeleteApiBangumiByIdResponse =
  DeleteApiBangumiByIdResponses[keyof DeleteApiBangumiByIdResponses];

export type GetBangumiData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type GetBangumiErrors = {
  /**
   * `id` not found
   */
  404: unknown;
};

export type GetBangumiResponses = {
  200: Bangumi;
};

export type GetBangumiResponse = GetBangumiResponses[keyof GetBangumiResponses];

export type UpdateBangumiData = {
  body?: UpdateBangumiDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type UpdateBangumiErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
  /**
   * `id` not found
   */
  404: unknown;
};

export type UpdateBangumiResponses = {
  200: Bangumi;
};

export type UpdateBangumiResponse =
  UpdateBangumiResponses[keyof UpdateBangumiResponses];

export type GetApiBangumiSubscriptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/bangumi/subscriptions";
};

export type GetApiBangumiSubscriptionsResponses = {
  200: Array<SubscribedBangumi>;
};

export type GetApiBangumiSubscriptionsResponse =
  GetApiBangumiSubscriptionsResponses[keyof GetApiBangumiSubscriptionsResponses];

export type DeleteApiBangumiSubscriptionsBySubscriptionIdData = {
  body?: never;
  path: {
    subscriptionId: number;
  };
  query?: never;
  url: "/api/bangumi/subscriptions/{subscriptionId}";
};

export type DeleteApiBangumiSubscriptionsBySubscriptionIdErrors = {
  /**
   * `subscriptionId` not found
   */
  404: unknown;
};

export type DeleteApiBangumiSubscriptionsBySubscriptionIdResponses = {
  204: void;
};

export type DeleteApiBangumiSubscriptionsBySubscriptionIdResponse =
  DeleteApiBangumiSubscriptionsBySubscriptionIdResponses[keyof DeleteApiBangumiSubscriptionsBySubscriptionIdResponses];

export type GetApiBangumiSubscriptionsBySubscriptionIdData = {
  body?: never;
  path: {
    subscriptionId: number;
  };
  query?: never;
  url: "/api/bangumi/subscriptions/{subscriptionId}";
};

export type GetApiBangumiSubscriptionsBySubscriptionIdErrors = {
  /**
   * `subscriptionId` not found
   */
  404: unknown;
};

export type GetApiBangumiSubscriptionsBySubscriptionIdResponses = {
  200: SubscribedBangumi;
};

export type GetApiBangumiSubscriptionsBySubscriptionIdResponse =
  GetApiBangumiSubscriptionsBySubscriptionIdResponses[keyof GetApiBangumiSubscriptionsBySubscriptionIdResponses];

export type PatchApiBangumiSubscriptionsBySubscriptionIdData = {
  body?: UpdateSubscriptionDto;
  path: {
    subscriptionId: number;
  };
  query?: never;
  url: "/api/bangumi/subscriptions/{subscriptionId}";
};

export type PatchApiBangumiSubscriptionsBySubscriptionIdErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
  /**
   * `subscriptionId` not found
   */
  404: unknown;
};

export type PatchApiBangumiSubscriptionsBySubscriptionIdResponses = {
  200: SubscribedBangumi;
};

export type PatchApiBangumiSubscriptionsBySubscriptionIdResponse =
  PatchApiBangumiSubscriptionsBySubscriptionIdResponses[keyof PatchApiBangumiSubscriptionsBySubscriptionIdResponses];

export type PostApiBangumiByIdSubscribeData = {
  body?: SubscribeDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}/subscribe";
};

export type PostApiBangumiByIdSubscribeErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
  /**
   * `id` not found
   */
  404: unknown;
};

export type PostApiBangumiByIdSubscribeResponses = {
  200: SubscribedBangumi;
};

export type PostApiBangumiByIdSubscribeResponse =
  PostApiBangumiByIdSubscribeResponses[keyof PostApiBangumiByIdSubscribeResponses];

export type GetCalendarData = {
  body?: never;
  path?: never;
  query?: {
    year?: number;
    season?: "winter" | "spring" | "summer" | "fall";
  };
  url: "/api/calendar";
};

export type GetCalendarErrors = {
  /**
   * Invalid `season` or `year`
   */
  400: unknown;
};

export type GetCalendarResponses = {
  200: Array<CalendarDay>;
};

export type GetCalendarResponse =
  GetCalendarResponses[keyof GetCalendarResponses];

export type RefreshCalendarData = {
  body?: never;
  path?: never;
  query?: {
    year?: number;
    season?: "winter" | "spring" | "summer" | "fall";
  };
  url: "/api/calendar/refresh";
};

export type RefreshCalendarErrors = {
  /**
   * Invalid `season` or `year`
   */
  400: unknown;
};

export type RefreshCalendarResponses = {
  200: Array<CalendarDay>;
};

export type RefreshCalendarResponse =
  RefreshCalendarResponses[keyof RefreshCalendarResponses];

export type PostApiCalendarQuickSubscribeData = {
  body?: QuickSubscribeDto;
  path?: never;
  query?: never;
  url: "/api/calendar/quick-subscribe";
};

export type PostApiCalendarQuickSubscribeErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type PostApiCalendarQuickSubscribeResponses = {
  200: SubscribedBangumi;
};

export type PostApiCalendarQuickSubscribeResponse =
  PostApiCalendarQuickSubscribeResponses[keyof PostApiCalendarQuickSubscribeResponses];

export type GetLogsData = {
  body?: never;
  path?: never;
  query: {
    date: string;
    level?: unknown;
    page?: number;
    pageSize?: number;
  };
  url: "/api/logs";
};

export type GetLogsErrors = {
  /**
   * Invalid `pageSize` or `page` or `level` or `date`
   */
  400: unknown;
};

export type GetLogsResponses = {
  200: LogsResponse;
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type StreamLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs/stream";
};

export type StreamLogsResponses = {
  200: Array<LogEntry>;
};

export type StreamLogsResponse = StreamLogsResponses[keyof StreamLogsResponses];

export type AddTorrentData = {
  body?: AddTorrentDto;
  path?: never;
  query?: never;
  url: "/api/torrent";
};

export type AddTorrentErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type AddTorrentResponses = {
  200: Torrent;
};

export type AddTorrentResponse = AddTorrentResponses[keyof AddTorrentResponses];

export type TestNotificationData = {
  body?: TestNotificationRequest;
  path?: never;
  query?: never;
  url: "/api/notification/test";
};

export type TestNotificationErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type TestNotificationResponses = {
  200: unknown;
};

export type GetEmbyLibrariesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/emby/libraries";
};

export type GetEmbyLibrariesResponses = {
  200: Array<EmbyLibraryInfo>;
};

export type GetEmbyLibrariesResponse =
  GetEmbyLibrariesResponses[keyof GetEmbyLibrariesResponses];

export type ImportEmbyData = {
  body?: ImportEmbyRequest;
  path?: never;
  query?: never;
  url: "/api/emby/import";
};

export type ImportEmbyErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type ImportEmbyResponses = {
  200: ImportResult;
};

export type ImportEmbyResponse = ImportEmbyResponses[keyof ImportEmbyResponses];

export type TestEmbyData = {
  body?: TestEmbyRequest;
  path?: never;
  query?: never;
  url: "/api/emby/test";
};

export type TestEmbyErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type TestEmbyResponses = {
  200: TestEmbyResponse;
};

export type TestEmbyResponse2 = TestEmbyResponses[keyof TestEmbyResponses];

export type PostApiDownloaderTestData = {
  body?: TestDownloaderRequest;
  path?: never;
  query?: never;
  url: "/api/downloader/test";
};

export type PostApiDownloaderTestErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type PostApiDownloaderTestResponses = {
  200: TestDownloaderResponse;
};

export type PostApiDownloaderTestResponse =
  PostApiDownloaderTestResponses[keyof PostApiDownloaderTestResponses];

export type GetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type GetSettingsResponses = {
  200: Settings;
};

export type GetSettingsResponse =
  GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
  body?: Settings;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type UpdateSettingsErrors = {
  /**
   * Invalid `body`
   */
  400: unknown;
};

export type UpdateSettingsResponses = {
  200: Settings;
};

export type UpdateSettingsResponse =
  UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetApiMetadataSearchBgmtvData = {
  body?: never;
  path?: never;
  query: {
    keyword: string;
  };
  url: "/api/metadata/search/bgmtv";
};

export type GetApiMetadataSearchBgmtvErrors = {
  /**
   * Invalid `keyword`
   */
  400: unknown;
};

export type GetApiMetadataSearchBgmtvResponses = {
  200: Array<BgmtvSearchItem>;
};

export type GetApiMetadataSearchBgmtvResponse =
  GetApiMetadataSearchBgmtvResponses[keyof GetApiMetadataSearchBgmtvResponses];

export type GetApiMetadataSearchTmdbData = {
  body?: never;
  path?: never;
  query: {
    keyword: string;
  };
  url: "/api/metadata/search/tmdb";
};

export type GetApiMetadataSearchTmdbErrors = {
  /**
   * Invalid `keyword`
   */
  400: unknown;
};

export type GetApiMetadataSearchTmdbResponses = {
  200: Array<TmdbSearchItem>;
};

export type GetApiMetadataSearchTmdbResponse =
  GetApiMetadataSearchTmdbResponses[keyof GetApiMetadataSearchTmdbResponses];

export type SearchMikanData = {
  body?: never;
  path?: never;
  query: {
    keyword: string;
  };
  url: "/api/metadata/mikan/search";
};

export type SearchMikanErrors = {
  /**
   * Invalid `keyword`
   */
  400: unknown;
};

export type SearchMikanResponses = {
  200: Array<MikanSearchResult>;
};

export type SearchMikanResponse =
  SearchMikanResponses[keyof SearchMikanResponses];

export type GetMikanRssData = {
  body?: never;
  path?: never;
  query: {
    id: string;
  };
  url: "/api/metadata/mikan/rss";
};

export type GetMikanRssErrors = {
  /**
   * Invalid `id`
   */
  400: unknown;
};

export type GetMikanRssResponses = {
  200: MikanBangumiDetail;
};

export type GetMikanRssResponse =
  GetMikanRssResponses[keyof GetMikanRssResponses];

export type GetEpisodesData = {
  body?: never;
  path: {
    subject_id: number;
  };
  query?: never;
  url: "/api/metadata/episodes/{subject_id}";
};

export type GetEpisodesErrors = {
  /**
   * `subject_id` not found
   */
  404: unknown;
};

export type GetEpisodesResponses = {
  200: Array<EpisodeInfo>;
};

export type GetEpisodesResponse =
  GetEpisodesResponses[keyof GetEpisodesResponses];

export type GetApiMetadataBangumiDataData = {
  body?: never;
  path?: never;
  query: {
    bgmtv_id: number;
    airdate: string;
  };
  url: "/api/metadata/bangumi-data";
};

export type GetApiMetadataBangumiDataErrors = {
  /**
   * Invalid `airdate` or `bgmtv_id`
   */
  400: unknown;
};

export type GetApiMetadataBangumiDataResponses = {
  200: CalendarItem;
};

export type GetApiMetadataBangumiDataResponse =
  GetApiMetadataBangumiDataResponses[keyof GetApiMetadataBangumiDataResponses];
