// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:3000" | (string & {});
};

/**
 * Bangumi (anime) main entity
 */
export type Bangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Auto download new episodes
   */
  auto_download: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  created_at: string;
  /**
   * Current downloaded episode
   */
  current_episode: number;
  /**
   * Episode offset
   */
  episode_offset: number;
  id: number;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * Custom save path (None=use default)
   */
  save_path?: string | null;
  /**
   * Season number
   */
  season: number;
  /**
   * Source type: webrip or bdrip
   */
  source_type: SourceType;
  /**
   * Chinese title (primary display)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes (0=unknown)
   */
  total_episodes: number;
  updated_at: string;
  /**
   * Year
   */
  year: number;
};

/**
 * Request body for creating a new bangumi
 */
export type CreateBangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Auto download new episodes
   */
  auto_download?: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  /**
   * Episode offset
   */
  episode_offset?: number;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * Custom save path
   */
  save_path?: string | null;
  /**
   * Season number (default: 1)
   */
  season?: number;
  /**
   * Source type
   */
  source_type?: SourceType;
  /**
   * Chinese title (required)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes
   */
  total_episodes?: number;
  /**
   * Year (required)
   */
  year: number;
};

/**
 * Episode item
 */
export type Episode = {
  /**
   * Air date
   */
  airdate: string;
  /**
   * Episode number
   */
  ep?: number | null;
  id: number;
  /**
   * Original name
   */
  name: string;
  /**
   * Chinese name
   */
  name_cn: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Episode type: 0=本篇, 1=SP, 2=OP, 3=ED
   */
  type: EpisodeType;
};

/**
 * Episode type
 */
export type EpisodeType = "Main" | "Special" | "Opening" | "Ending";

/**
 * Platform type for subjects
 */
export type Platform = "TV" | "Web" | "DLC" | "剧场版" | "Unknown";

/**
 * Search response from POST /v0/search/subjects
 */
export type SearchSubjectsResponse = {
  data: Array<Subject>;
  limit: number;
  offset: number;
  total: number;
};

/**
 * Source type for bangumi
 */
export type SourceType = "webrip" | "bdrip";

/**
 * Subject item in search results
 */
export type Subject = {
  date?: string | null;
  eps: number;
  id: number;
  image?: string | null;
  name: string;
  name_cn: string;
  platform?: null | Platform;
};

export type TvShow = {
  backdrop_path?: string | null;
  first_air_date?: string | null;
  genre_ids: Array<number>;
  id: number;
  name: string;
  origin_country: Array<string>;
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path?: string | null;
  vote_average: number;
  vote_count: number;
};

export type CreateBangumiData = {
  body: CreateBangumi;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type CreateBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type CreateBangumiResponses = {
  /**
   * Bangumi created successfully
   */
  201: Bangumi;
};

export type CreateBangumiResponse =
  CreateBangumiResponses[keyof CreateBangumiResponses];

export type GetEpisodesData = {
  body?: never;
  path: {
    /**
     * BGM.tv subject ID
     */
    subject_id: number;
  };
  query?: never;
  url: "/api/episodes/{subject_id}";
};

export type GetEpisodesErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetEpisodesResponses = {
  /**
   * Episodes list
   */
  200: Array<Episode>;
};

export type GetEpisodesResponse =
  GetEpisodesResponses[keyof GetEpisodesResponses];

export type SearchBangumiData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search for bangumi
     */
    keyword: string;
  };
  url: "/api/search/bgmtv";
};

export type SearchBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchBangumiResponses = {
  /**
   * Search results
   */
  200: Array<Subject>;
};

export type SearchBangumiResponse =
  SearchBangumiResponses[keyof SearchBangumiResponses];

export type SearchTmdbData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search for anime on TMDB
     */
    keyword: string;
  };
  url: "/api/search/tmdb";
};

export type SearchTmdbErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchTmdbResponses = {
  /**
   * Search results from TMDB
   */
  200: Array<TvShow>;
};

export type SearchTmdbResponse = SearchTmdbResponses[keyof SearchTmdbResponses];
