// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  addTorrent,
  createBangumi,
  deleteApiBangumiById,
  deleteApiBangumiSubscriptionsBySubscriptionId,
  getApiBangumiSubscriptions,
  getApiBangumiSubscriptionsBySubscriptionId,
  getApiMetadataBangumiData,
  getApiMetadataSearchBgmtv,
  getApiMetadataSearchTmdb,
  getBangumi,
  getCalendar,
  getEmbyLibraries,
  getEpisodes,
  getLogs,
  getMikanRss,
  getSettings,
  importEmby,
  listBangumi,
  listSeries,
  type Options,
  patchApiBangumiSubscriptionsBySubscriptionId,
  postApiBangumiByIdSubscribe,
  postApiCalendarQuickSubscribe,
  postApiDownloaderTest,
  refreshCalendar,
  searchMikan,
  testEmby,
  testNotification,
  updateBangumi,
  updateSettings,
} from "../sdk.gen";
import type {
  AddTorrentData,
  AddTorrentResponse,
  CreateBangumiData,
  CreateBangumiResponse,
  DeleteApiBangumiByIdData,
  DeleteApiBangumiByIdResponse,
  DeleteApiBangumiSubscriptionsBySubscriptionIdData,
  DeleteApiBangumiSubscriptionsBySubscriptionIdResponse,
  GetApiBangumiSubscriptionsBySubscriptionIdData,
  GetApiBangumiSubscriptionsBySubscriptionIdResponse,
  GetApiBangumiSubscriptionsData,
  GetApiBangumiSubscriptionsResponse,
  GetApiMetadataBangumiDataData,
  GetApiMetadataBangumiDataResponse,
  GetApiMetadataSearchBgmtvData,
  GetApiMetadataSearchBgmtvResponse,
  GetApiMetadataSearchTmdbData,
  GetApiMetadataSearchTmdbResponse,
  GetBangumiData,
  GetBangumiResponse,
  GetCalendarData,
  GetCalendarResponse,
  GetEmbyLibrariesData,
  GetEmbyLibrariesResponse,
  GetEpisodesData,
  GetEpisodesResponse,
  GetLogsData,
  GetLogsResponse,
  GetMikanRssData,
  GetMikanRssResponse,
  GetSettingsData,
  GetSettingsResponse,
  ImportEmbyData,
  ImportEmbyResponse,
  ListBangumiData,
  ListBangumiResponse,
  ListSeriesData,
  ListSeriesResponse,
  PatchApiBangumiSubscriptionsBySubscriptionIdData,
  PatchApiBangumiSubscriptionsBySubscriptionIdResponse,
  PostApiBangumiByIdSubscribeData,
  PostApiBangumiByIdSubscribeResponse,
  PostApiCalendarQuickSubscribeData,
  PostApiCalendarQuickSubscribeResponse,
  PostApiDownloaderTestData,
  PostApiDownloaderTestResponse,
  RefreshCalendarData,
  RefreshCalendarResponse,
  SearchMikanData,
  SearchMikanResponse,
  TestEmbyData,
  TestEmbyResponse2,
  TestNotificationData,
  UpdateBangumiData,
  UpdateBangumiResponse,
  UpdateSettingsData,
  UpdateSettingsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listSeriesQueryKey = (options?: Options<ListSeriesData>) =>
  createQueryKey("listSeries", options);

/**
 * Get all series
 */
export const listSeriesOptions = (options?: Options<ListSeriesData>) =>
  queryOptions<
    ListSeriesResponse,
    DefaultError,
    ListSeriesResponse,
    ReturnType<typeof listSeriesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSeries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSeriesQueryKey(options),
  });

export const listBangumiQueryKey = (options?: Options<ListBangumiData>) =>
  createQueryKey("listBangumi", options);

/**
 * Get all bangumi metadata
 */
export const listBangumiOptions = (options?: Options<ListBangumiData>) =>
  queryOptions<
    ListBangumiResponse,
    DefaultError,
    ListBangumiResponse,
    ReturnType<typeof listBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listBangumiQueryKey(options),
  });

/**
 * Create a new bangumi (metadata only)
 */
export const createBangumiMutation = (
  options?: Partial<Options<CreateBangumiData>>,
): UseMutationOptions<
  CreateBangumiResponse,
  DefaultError,
  Options<CreateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBangumiResponse,
    DefaultError,
    Options<CreateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete bangumi
 */
export const deleteApiBangumiByIdMutation = (
  options?: Partial<Options<DeleteApiBangumiByIdData>>,
): UseMutationOptions<
  DeleteApiBangumiByIdResponse,
  DefaultError,
  Options<DeleteApiBangumiByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiBangumiByIdResponse,
    DefaultError,
    Options<DeleteApiBangumiByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiBangumiById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBangumiQueryKey = (options: Options<GetBangumiData>) =>
  createQueryKey("getBangumi", options);

/**
 * Get bangumi by ID
 */
export const getBangumiOptions = (options: Options<GetBangumiData>) =>
  queryOptions<
    GetBangumiResponse,
    DefaultError,
    GetBangumiResponse,
    ReturnType<typeof getBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiQueryKey(options),
  });

/**
 * Update bangumi metadata
 */
export const updateBangumiMutation = (
  options?: Partial<Options<UpdateBangumiData>>,
): UseMutationOptions<
  UpdateBangumiResponse,
  DefaultError,
  Options<UpdateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBangumiResponse,
    DefaultError,
    Options<UpdateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiBangumiSubscriptionsQueryKey = (
  options?: Options<GetApiBangumiSubscriptionsData>,
) => createQueryKey("getApiBangumiSubscriptions", options);

/**
 * Get all subscribed bangumi
 */
export const getApiBangumiSubscriptionsOptions = (
  options?: Options<GetApiBangumiSubscriptionsData>,
) =>
  queryOptions<
    GetApiBangumiSubscriptionsResponse,
    DefaultError,
    GetApiBangumiSubscriptionsResponse,
    ReturnType<typeof getApiBangumiSubscriptionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiBangumiSubscriptions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiBangumiSubscriptionsQueryKey(options),
  });

/**
 * Unsubscribe from a bangumi
 */
export const deleteApiBangumiSubscriptionsBySubscriptionIdMutation = (
  options?: Partial<Options<DeleteApiBangumiSubscriptionsBySubscriptionIdData>>,
): UseMutationOptions<
  DeleteApiBangumiSubscriptionsBySubscriptionIdResponse,
  DefaultError,
  Options<DeleteApiBangumiSubscriptionsBySubscriptionIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiBangumiSubscriptionsBySubscriptionIdResponse,
    DefaultError,
    Options<DeleteApiBangumiSubscriptionsBySubscriptionIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiBangumiSubscriptionsBySubscriptionId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiBangumiSubscriptionsBySubscriptionIdQueryKey = (
  options: Options<GetApiBangumiSubscriptionsBySubscriptionIdData>,
) => createQueryKey("getApiBangumiSubscriptionsBySubscriptionId", options);

/**
 * Get subscription by ID
 */
export const getApiBangumiSubscriptionsBySubscriptionIdOptions = (
  options: Options<GetApiBangumiSubscriptionsBySubscriptionIdData>,
) =>
  queryOptions<
    GetApiBangumiSubscriptionsBySubscriptionIdResponse,
    DefaultError,
    GetApiBangumiSubscriptionsBySubscriptionIdResponse,
    ReturnType<typeof getApiBangumiSubscriptionsBySubscriptionIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiBangumiSubscriptionsBySubscriptionId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiBangumiSubscriptionsBySubscriptionIdQueryKey(options),
  });

/**
 * Update a subscription
 */
export const patchApiBangumiSubscriptionsBySubscriptionIdMutation = (
  options?: Partial<Options<PatchApiBangumiSubscriptionsBySubscriptionIdData>>,
): UseMutationOptions<
  PatchApiBangumiSubscriptionsBySubscriptionIdResponse,
  DefaultError,
  Options<PatchApiBangumiSubscriptionsBySubscriptionIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchApiBangumiSubscriptionsBySubscriptionIdResponse,
    DefaultError,
    Options<PatchApiBangumiSubscriptionsBySubscriptionIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiBangumiSubscriptionsBySubscriptionId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Subscribe to a bangumi
 */
export const postApiBangumiByIdSubscribeMutation = (
  options?: Partial<Options<PostApiBangumiByIdSubscribeData>>,
): UseMutationOptions<
  PostApiBangumiByIdSubscribeResponse,
  DefaultError,
  Options<PostApiBangumiByIdSubscribeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiBangumiByIdSubscribeResponse,
    DefaultError,
    Options<PostApiBangumiByIdSubscribeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiBangumiByIdSubscribe({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCalendarQueryKey = (options?: Options<GetCalendarData>) =>
  createQueryKey("getCalendar", options);

/**
 * Get seasonal calendar
 *
 * Get bangumi calendar for a specific year and season
 */
export const getCalendarOptions = (options?: Options<GetCalendarData>) =>
  queryOptions<
    GetCalendarResponse,
    DefaultError,
    GetCalendarResponse,
    ReturnType<typeof getCalendarQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCalendar({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCalendarQueryKey(options),
  });

/**
 * Refresh calendar data
 *
 * Fetch fresh data from Mikan and update local calendar
 */
export const refreshCalendarMutation = (
  options?: Partial<Options<RefreshCalendarData>>,
): UseMutationOptions<
  RefreshCalendarResponse,
  DefaultError,
  Options<RefreshCalendarData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshCalendarResponse,
    DefaultError,
    Options<RefreshCalendarData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshCalendar({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Quick subscribe from calendar
 *
 * Create bangumi and subscription in one call with auto-generated Mikan RSS URL
 */
export const postApiCalendarQuickSubscribeMutation = (
  options?: Partial<Options<PostApiCalendarQuickSubscribeData>>,
): UseMutationOptions<
  PostApiCalendarQuickSubscribeResponse,
  DefaultError,
  Options<PostApiCalendarQuickSubscribeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiCalendarQuickSubscribeResponse,
    DefaultError,
    Options<PostApiCalendarQuickSubscribeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiCalendarQuickSubscribe({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getLogsQueryKey = (options: Options<GetLogsData>) =>
  createQueryKey("getLogs", options);

/**
 * Get logs by date
 *
 * Query log entries for a specific date with optional level filtering and pagination
 */
export const getLogsOptions = (options: Options<GetLogsData>) =>
  queryOptions<
    GetLogsResponse,
    DefaultError,
    GetLogsResponse,
    ReturnType<typeof getLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLogsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getLogsInfiniteQueryKey = (
  options: Options<GetLogsData>,
): QueryKey<Options<GetLogsData>> => createQueryKey("getLogs", options, true);

/**
 * Get logs by date
 *
 * Query log entries for a specific date with optional level filtering and pagination
 */
export const getLogsInfiniteOptions = (options: Options<GetLogsData>) =>
  infiniteQueryOptions<
    GetLogsResponse,
    DefaultError,
    InfiniteData<GetLogsResponse>,
    QueryKey<Options<GetLogsData>>,
    | number
    | Pick<
        QueryKey<Options<GetLogsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetLogsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getLogs({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getLogsInfiniteQueryKey(options),
    },
  );

/**
 * Manually add a torrent download
 */
export const addTorrentMutation = (
  options?: Partial<Options<AddTorrentData>>,
): UseMutationOptions<
  AddTorrentResponse,
  DefaultError,
  Options<AddTorrentData>
> => {
  const mutationOptions: UseMutationOptions<
    AddTorrentResponse,
    DefaultError,
    Options<AddTorrentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addTorrent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test Telegram notification by sending a test message
 */
export const testNotificationMutation = (
  options?: Partial<Options<TestNotificationData>>,
): UseMutationOptions<unknown, DefaultError, Options<TestNotificationData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<TestNotificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testNotification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEmbyLibrariesQueryKey = (
  options?: Options<GetEmbyLibrariesData>,
) => createQueryKey("getEmbyLibraries", options);

/**
 * Get Emby libraries
 *
 * Get list of TV show libraries from Emby
 */
export const getEmbyLibrariesOptions = (
  options?: Options<GetEmbyLibrariesData>,
) =>
  queryOptions<
    GetEmbyLibrariesResponse,
    DefaultError,
    GetEmbyLibrariesResponse,
    ReturnType<typeof getEmbyLibrariesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEmbyLibraries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEmbyLibrariesQueryKey(options),
  });

/**
 * Import Bangumi from Emby media library
 *
 * Import anime from Emby. Optionally specify library IDs to import from.
 */
export const importEmbyMutation = (
  options?: Partial<Options<ImportEmbyData>>,
): UseMutationOptions<
  ImportEmbyResponse,
  DefaultError,
  Options<ImportEmbyData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportEmbyResponse,
    DefaultError,
    Options<ImportEmbyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importEmby({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test Emby connection
 *
 * Test connection to Emby server with provided settings
 */
export const testEmbyMutation = (
  options?: Partial<Options<TestEmbyData>>,
): UseMutationOptions<
  TestEmbyResponse2,
  DefaultError,
  Options<TestEmbyData>
> => {
  const mutationOptions: UseMutationOptions<
    TestEmbyResponse2,
    DefaultError,
    Options<TestEmbyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testEmby({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test qBittorrent connection
 *
 * Test connection and authentication to qBittorrent with provided settings
 */
export const postApiDownloaderTestMutation = (
  options?: Partial<Options<PostApiDownloaderTestData>>,
): UseMutationOptions<
  PostApiDownloaderTestResponse,
  DefaultError,
  Options<PostApiDownloaderTestData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiDownloaderTestResponse,
    DefaultError,
    Options<PostApiDownloaderTestData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiDownloaderTest({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSettingsQueryKey = (options?: Options<GetSettingsData>) =>
  createQueryKey("getSettings", options);

/**
 * Get current settings
 *
 * Retrieve the current application settings
 */
export const getSettingsOptions = (options?: Options<GetSettingsData>) =>
  queryOptions<
    GetSettingsResponse,
    DefaultError,
    GetSettingsResponse,
    ReturnType<typeof getSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSettingsQueryKey(options),
  });

/**
 * Update settings
 *
 * Update the application settings (full replacement)
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>,
): UseMutationOptions<
  UpdateSettingsResponse,
  DefaultError,
  Options<UpdateSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    DefaultError,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiMetadataSearchBgmtvQueryKey = (
  options: Options<GetApiMetadataSearchBgmtvData>,
) => createQueryKey("getApiMetadataSearchBgmtv", options);

/**
 * Search bangumi metadata from BGM.tv
 */
export const getApiMetadataSearchBgmtvOptions = (
  options: Options<GetApiMetadataSearchBgmtvData>,
) =>
  queryOptions<
    GetApiMetadataSearchBgmtvResponse,
    DefaultError,
    GetApiMetadataSearchBgmtvResponse,
    ReturnType<typeof getApiMetadataSearchBgmtvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiMetadataSearchBgmtv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiMetadataSearchBgmtvQueryKey(options),
  });

export const getApiMetadataSearchTmdbQueryKey = (
  options: Options<GetApiMetadataSearchTmdbData>,
) => createQueryKey("getApiMetadataSearchTmdb", options);

/**
 * Search bangumi metadata from TMDB
 */
export const getApiMetadataSearchTmdbOptions = (
  options: Options<GetApiMetadataSearchTmdbData>,
) =>
  queryOptions<
    GetApiMetadataSearchTmdbResponse,
    DefaultError,
    GetApiMetadataSearchTmdbResponse,
    ReturnType<typeof getApiMetadataSearchTmdbQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiMetadataSearchTmdb({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiMetadataSearchTmdbQueryKey(options),
  });

export const searchMikanQueryKey = (options: Options<SearchMikanData>) =>
  createQueryKey("searchMikan", options);

/**
 * Search bangumi on Mikan
 */
export const searchMikanOptions = (options: Options<SearchMikanData>) =>
  queryOptions<
    SearchMikanResponse,
    DefaultError,
    SearchMikanResponse,
    ReturnType<typeof searchMikanQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchMikan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchMikanQueryKey(options),
  });

export const getMikanRssQueryKey = (options: Options<GetMikanRssData>) =>
  createQueryKey("getMikanRss", options);

/**
 * Get Mikan bangumi detail with RSS URLs
 */
export const getMikanRssOptions = (options: Options<GetMikanRssData>) =>
  queryOptions<
    GetMikanRssResponse,
    DefaultError,
    GetMikanRssResponse,
    ReturnType<typeof getMikanRssQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMikanRss({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMikanRssQueryKey(options),
  });

export const getEpisodesQueryKey = (options: Options<GetEpisodesData>) =>
  createQueryKey("getEpisodes", options);

/**
 * Get episodes for a BGM.tv subject
 */
export const getEpisodesOptions = (options: Options<GetEpisodesData>) =>
  queryOptions<
    GetEpisodesResponse,
    DefaultError,
    GetEpisodesResponse,
    ReturnType<typeof getEpisodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEpisodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEpisodesQueryKey(options),
  });

export const getApiMetadataBangumiDataQueryKey = (
  options: Options<GetApiMetadataBangumiDataData>,
) => createQueryKey("getApiMetadataBangumiData", options);

/**
 * Lookup bangumi-data entry by BGM.tv ID and air date
 *
 * Uses airdate to determine which seasonal JSON file to fetch, then searches for matching bgmtv_id
 */
export const getApiMetadataBangumiDataOptions = (
  options: Options<GetApiMetadataBangumiDataData>,
) =>
  queryOptions<
    GetApiMetadataBangumiDataResponse,
    DefaultError,
    GetApiMetadataBangumiDataResponse,
    ReturnType<typeof getApiMetadataBangumiDataQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiMetadataBangumiData({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiMetadataBangumiDataQueryKey(options),
  });
