// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import { type Options, Sdk } from "../sdk.gen";
import type {
  CreateBangumiData,
  CreateBangumiResponse,
  GetEpisodesData,
  GetEpisodesResponse,
  SearchBangumiData,
  SearchBangumiResponse,
  SearchTmdbData,
  SearchTmdbResponse,
} from "../types.gen";

/**
 * Create a new bangumi
 */
export const createBangumiMutation = (
  options?: Partial<Options<CreateBangumiData>>,
): UseMutationOptions<
  CreateBangumiResponse,
  DefaultError,
  Options<CreateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBangumiResponse,
    DefaultError,
    Options<CreateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Sdk.__registry.get().createBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getEpisodesQueryKey = (options: Options<GetEpisodesData>) =>
  createQueryKey("getEpisodes", options);

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodesOptions = (options: Options<GetEpisodesData>) =>
  queryOptions<
    GetEpisodesResponse,
    DefaultError,
    GetEpisodesResponse,
    ReturnType<typeof getEpisodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry.get().getEpisodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEpisodesQueryKey(options),
  });

export const searchBangumiQueryKey = (options: Options<SearchBangumiData>) =>
  createQueryKey("searchBangumi", options);

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBangumiOptions = (options: Options<SearchBangumiData>) =>
  queryOptions<
    SearchBangumiResponse,
    DefaultError,
    SearchBangumiResponse,
    ReturnType<typeof searchBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry.get().searchBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchBangumiQueryKey(options),
  });

export const searchTmdbQueryKey = (options: Options<SearchTmdbData>) =>
  createQueryKey("searchTmdb", options);

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdbOptions = (options: Options<SearchTmdbData>) =>
  queryOptions<
    SearchTmdbResponse,
    DefaultError,
    SearchTmdbResponse,
    ReturnType<typeof searchTmdbQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Sdk.__registry.get().searchTmdb({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchTmdbQueryKey(options),
  });
